## Welcome to Jupyter!

Jupyter divides Python code into neat units called a cell. There are two types of cell! 

Markup cells contain text, like this cell. Double click them to edit the text, and then press **`<Shift> + <Enter>`** to render it with formatting. Try double-clicking this text, then pressing **`<Shift> + <Enter>`**!

Code cells contain executable python code. Click them to edit the code, then press **`<Shift> + <Enter>`** to execute the block. Try it out below!



In [1]:
print("Hi, I'm a code cell! Click me and press shift + enter.")

Hi, I'm a code cell! Click me and press shift + enter.


You can add new cells using the plus sign on the menu above. 

Take a few minutes to look at the different options offered in the menu! There are a few that are especially useful: 

- File Menu 
    - "Download As" lets you save your notebook to your computer as a .ipynb file.
- Kernel Menu
    - "Restart the kernel" clears the output of every cell. Can be useful if your code gets stuck!
- Cell Menu
    - "Cell Type" lets you change the type of cell you are working with, between code and markup. 



## Libraries ##

Remember learning about libraries? Today we're going to practice using numpy and nltk, two helpful libraries for natural language processing. 
Some things to keep in mind: 
- Objects vs attributes vs methods
    - **Objects** are instances of something called a **class**. All objects of the same class have similar properties, but different specific values. For example, think about a car. The class Car might have some rules: 4 wheels, metal body, steering wheel. Specific instances of Cars, Car objects, could be very different (a gray Toyota, a blue SmartCar, a red Ferrari) but all of them follow the rules of the Car class. 
    - ** Attributes ** are some of what make these cars different! For example, the class Car might have an attribute color. Ferrari.color would be red, while Toyota.color would be gray. You can set or get the value of an attribute by using the syntax variable.attribute 
    - ** Methods ** are very similar to ** functions **, which you already learned about. Like a function, a method is a command to perform a sequence of actions that can accept ** arguments ** inside of the parenthesis that follow it. The only difference between the two:
        - A **method** is a function performed on or by an object. For example, ferrari.drive() might be a method that makes a specific car drive. 
        - A **function** stands on its own. print("Hello, World!") doesn't act on an object, it just does something. 
    
These distinctions can be confusing (even for computer scientists!), so don't be afraid to ask. 

## Importing modules

- Modules are pre-packaged groups of Python files that you can import
- Modules contain classes (with attributes and methods), functions, and sometimes datasets
- After importing a module, you can use all of these without having to write them yourself
- Here is a simple example of importing and using a module called numpy, which provides support for lots of different calculations and mathematical data structures:

In [30]:
# This line does the importing!
import numpy as np
# The format is: "import (packagename) as (name you want to use for package in code).
# If you leave the second part out, it will be called by its original name
# i.e. if you said "import numpy", you would use numpy to refer to the package 

# Here is an example of making an instance of a numpy ndarray, a class that represents a mathematical array
# It can be an array of any dimensions that can hold any objects of the same type, but is usually used to hold numbers 
# Numpy provides a lot of useful mathematical functions that take ndarrays as arguments. 
,
ex_array = np.array([[2,2,3],[4,5,6]])    # Each layer of square brackets is another dimension within the array

print("Type: ")
print(type(ex_array))            # Prints "<class 'numpy.ndarray'>"

print("Shape: ")
print(ex_array.shape)  # Shape returns the dimensions of an array, so this prints "(2, 3)"

print("Old: ")
print(ex_array)   # Using square brackets gives you the elements at that index, so this prints "1 2 4"

# You can index arrays using [a, b, ..... z] with as many dimensions as you want to specify.
ex_array[0,0] = 1   # Using the assignment operator changes the values in the array. Here, we change the 1st item. 
print("New: ")
print(ex_array)


Type: 
<class 'numpy.ndarray'>
Shape: 
(2, 3)
Old: 
[[2 2 3]
 [4 5 6]]
New: 
[[1 2 3]
 [4 5 6]]


- To learn about what different functions or objects a module contains, you have to consult its documentation. For example, here is a link to the numpy documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/
- Click the link that says "N-Dimensional Arrays" under the heading"Arrays" to learn more about the ndarray. 
- Try to find the methods or attributes from the documentation to do the following things with the ex_array. 

In [22]:
# Find the number of elements in an array
num_elements = ex_array.size
print("Your answer: " + str(num_elements) + "; correct answer: 6")

# Find the index of the maximum value
max_ind = ex_array.argmax()
print("Your answer: " + str(max_ind) + "; correct answer: 5")

# Reshape the array so that it is of dimension 3 x 2
re_ex_array = ex_array.reshape(3, 2)
print("Your answer: \n" + str(re_ex_array) + ", \n the correct answer: \n [[1 2] \n [3 4] \n [5 6]]")

Your answer: 6; correct answer: 6
Your answer: 5; correct answer: 5
Your answer: 
[[1 2]
 [3 4]
 [5 6]], 
 the correct answer: 
 [[1 2] 
 [3 4] 
 [5 6]]


Numpy also includes a lot of functions for doing statistical calculations. Take a look at the "Statistics" section to see some of the options. Can you predict what each of the following lines will print out?

In [23]:
print(np.mean(ex_array))

3.5


In [25]:
print(np.std(ex_array))

1.70782512766
