# Welcome to Jupyter!

Jupyter notebooks are a way of running Python code online. They divide code up into independent cells that work together. 

Markup cells contain text, like this cell. Double click them to edit the text, and then press **`<Shift> + <Enter>`** to render it with formatting. Try double-clicking this text!

Code cells contain executable python code. Click them to edit the code, then press **`<Shift> + <Enter>`** to execute the block. Try it out below!



In [3]:
print("Hi, I'm a code cell! Click me and press enter.")

Hi, I'm a code cell! Click me and press enter.


You can add new cells using the plus sign on the menu above. Take a few minutes to look at the different options offered in the menu! There are a few that are especially useful: 

- File Menu 
    - "Download As" lets you save your notebook to your computer as a .ipynb file
- Kernel Menu
    - "Restart the kernel" clears the output of every cell. Can be useful if your code gets stuck!
- Cell Menu
    - "Cell Type" lets you change the type of cell you are working with



# Python

The language we'll be working on for the project is called Python. Today's workbook is designed to familiarize you with some basic elements of Python and let you experiment with Jupyter notebook. You won't be asked to write much code, and you'll get a much more thorough introduction to Python tomorrow, so don't worry too much if certain things are confusing. 

## Variables and Built-ins

One of the most basic elements of a programming language like Python is the **variable**. A **variable** is a name that refers to a specific ** object**, ** object instance**, or **object value**. The name is like a shorthand, easier to type and easier to remember what it's supposed to store. 

We'll talk more about what objects are later, but the first thing to know is that Python provides several basic types of object, which are known as **built-ins** because they're built into the language. Each built-in stores a different type of information and has different properties. 

Here are some useful basic types to know: 

- **`str`** (string; a sequence of characters enclosed in single quotes, double quotes, or triple quotes. These are like words and sentences)
  - `'this is a string using single quotes'`
  - `"this is a string using double quotes"`
  - `'''this is a triple quoted string using single quotes'''`
  - `"""this is a triple quoted string using double quotes"""`
- **`int`** (integer; a whole number with no decimal place)
  - `10`
  - `-3`
- **`float`** (float; a number that has a decimal place)
  - `7.41`
  - `-0.006`
- **`bool`** (boolean; a binary value that is either true or false)
  - `True`
  - `False`
  


In [6]:
# Here are examples of some of the basic types
example_str = "I am a Python string"
example_int = 10
example_float = 6.5
example_bool = True

# We can use the print function to print out the value of any variable, like this
print(example_str)

# It's much easier than typing it out every time!

I am a Python string


In [ ]:
# Try printing out the value of another one of the variables here

## Operators

The equals sign is called the **assignment operator**, but there are lots of other operators that you can use on variables. Some operators work differently on different types, like **arithmetic operators**
  - **`+`** (addition)
  - **`-`** (subtraction)
  - **`*`** (multiplication)
  - **`/`** (division)
  - __`**`__ (exponent)
  
While some work pretty much the same on any type, like **comparison operators** (which return a bool, `True` or `False`)
  - **`==`** (equal to)
  - **`!=`** (not equal to)
  - **`<`** (less than)
  - **`<=`** (less than or equal to)
  - **`>`** (greater than)
  - **`>=`** (greater than or equal to)

In [7]:
# An arithmetic operator works like this on an int
print(example_int + 4)

14
I am a Python string with a little extra at the end'


In [ ]:
# While on a string it looks like this
print(example_str + " with a little extra at the end")

In [8]:
# How does boolean addition work? Guess what the pattern of output will be
print(True + True)
print(True + False)
print(False + False)

2
1
0


In [10]:
# Not every arithmetic operator works on every type. You can't do this, for example
print(example_str - " less a little at the end")

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [12]:
# You also can't use these operators on two objects of different types
# Sometimes it looks like you should be able to:
print("3" + 4)

TypeError: must be str, not int

## Functions

Another way to operate with variables in Python is to use them as arguments to functions. Functions take the form
    
    functionname(argument1, argument2, ...)
    
Functions can have no arguments or many, and you can pass them variables as arguments. They are just a way to package a multistep operation into a single easily-callable name. For example, every time you want to print something to the console, you call print(output), rather than telling the computer exactly how to write output, every time. 

Soon you'll be writing your own functions, but for now you just need to recognize them and know how to use existing functions. 

## Objects

If you're feeling a little restricted by the built-in types, never fear! Python also offers you and others the ability to create your own **objects**, which are like built-ins but customized. 
    
   - **Objects** are instances of something called a **class**. All objects of the same class have similar properties, but different specific values. For example, think about a car.  
       - All cars (all instances of class Car) have some properties in common: 4 wheels, metal body, steering wheel. 
       - However, specific instances of Car, have some different properties (a gray Toyota, a blue SmartCar, a red Ferrari) 
   - ** Attributes ** are some of what make these cars different! For example, the class Car might have an attribute color. Ferrari.color would be red, while Toyota.color would be gray. You can set or get the value of an attribute by using the syntax variable.attribute 
   - ** Methods ** are very similar to ** functions **, which you have been using already. Methods and functions are commands to perform a sequence of actions that can accept ** arguments ** inside of the parenthesis that follow it. For example, you've been using print("this and that"). Here, print is the function, and "this and that" is the argument. 
       - A **method** is a function performed on or by an object. For example, ferrari.drive() might be a method that makes a specific car drive. 
       - A **function** stands on its own. print("Hello, World!") doesn't act on an object, it just does something. 
    
These distinctions can be confusing (even for computer scientists!), so don't be afraid to ask. 

## Importing modules
If you want to use different kinds of object, but don't know where to begin building them, we have good news! There's a good chance somebody has already built something that would be useful to you, and Python makes it easy to use that code through something called a **module**. 
- Modules are pre-packaged groups of Python files that you can import
- Modules contain classes (with attributes and methods), functions, and sometimes datasets
- After importing a module, you can use all of these without having to write them yourself
- Here is a simple example of importing and using a module called numpy, which provides support for lots of different calculations and mathematical data structures:

In [15]:
# This line does the importing!
import numpy as np
# The format is: "import (packagename) as (name you want to use for package in code).
# If you leave the second part out, it will be called by its original name
# i.e. if you said "import numpy", you would use numpy to refer to the package 

# Here is an example of making an instance of a numpy ndarray, a class that represents a mathematical array
# It can be an array of any dimensions that can hold any objects of the same type, but is usually used to hold numbers 
# Numpy provides a lot of useful mathematical functions that take ndarrays as arguments. 
,
ex_array = np.array([[2,2,3],[4,5,6]])    # Each layer of square brackets is another dimension within the array

# Here, we print out one of the attributes of the object
print("Shape: ")
print(ex_array.shape)  # Shape returns the dimensions of an array, so this prints "(2, 3)"

# Here, we print out the first version of the array
print("Old: ")
print(ex_array)   # Using square brackets gives you the elements at that index, so this prints "1 2 4"

# You can index arrays using [a, b, ..... z] with as many dimensions as you want to specify.
ex_array[0,0] = 1   # Using the assignment operator changes the values in the array. Here, we change the 1st item. 
print("New: ")
print(ex_array)

Shape: 
(2, 3)
Old: 
[[2 2 3]
 [4 5 6]]
New: 
[[1 2 3]
 [4 5 6]]


- To learn about what different functions or objects a module contains, you have to consult its documentation. For example, here is a link to the numpy documentation: https://docs.scipy.org/doc/numpy-1.14.0/reference/
- Click the link that says "N-Dimensional Arrays" under the heading"Arrays" to learn more about the ndarray. 
- Try to find the methods or attributes from the documentation to do the following things with the ex_array. 

In [16]:
# Find the number of elements in an array
num_elements = 0
print("Your answer: " + str(num_elements) + "; correct answer: 6")

# Find the index of the maximum value
max_ind = 0
print("Your answer: " + str(max_ind) + "; correct answer: 5")

# Reshape the array so that it is of dimension 3 x 2
re_ex_array = []
print("Your answer: \n" + str(re_ex_array) + ", \n the correct answer: \n [[1 2] \n [3 4] \n [5 6]]")

Your answer: 6; correct answer: 6
Your answer: 5; correct answer: 5
Your answer: 
[[1 2]
 [3 4]
 [5 6]], 
 the correct answer: 
 [[1 2] 
 [3 4] 
 [5 6]]


Numpy also includes a lot of functions for doing statistical calculations. Take a look at the "Statistics" section to see some of the options. Can you predict what each of the following lines will print out?

In [ ]:
print(np.mean(ex_array))

In [ ]:
print(np.std(ex_array))

Numpy is one of the most popular packages in Python, but it is far from the only one. In the next few days you'll learn about others that will be helpful for natural language processing. 

## Conclusion

Don't worry if you don't feel comfortable writing your own code yet. This was a basic high-level overview of some of the information we'll be covering in the coming days. 